# Site settings
title: Elizabeth Naibor
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Naibor Elizabeth
user_description: I\'m a self-taught Software Engineer, always searching for the next challenge;I believe in learning and the learning process
user_title: Software Engineer
email: naiborleona.nl@gmail.com
twitter_username: leona_naibor
github_username:  naibor
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
